Object Pair Constraints
Applied-Ontology-Education/Logic-for-Ontologists-Fall-2024 pull request #7
Opened 2024-09-17 18:02 UTC by RobertElliottKrieter

Criticism gladly accepted. My apologies if formatting is rough-- still getting accustomed to GitHub.

2024-09-17 18:30 UTC, RobertElliottKrieter commented on Assignment Part One: Object-Property Pai.html — Logic-for-Ontologists-Fall-2024 [Codespaces: supreme.html
> +For example, John (x) is connected to Mary (y) by object-property "has father" is unique.
Switch Mary with Steve or vis a versa. For every (y) related to (x) there can only be one (x) who hold this property relation

2024-09-18 17:59 UTC, RobertElliottKrieter commented on Assignment Part One: Object-Property Pai.html — Logic-for-Ontologists-Fall-2024 [Codespaces: supreme.html
> +For example, John (x) is connected to Mary (y) by object-property "has father" is unique.
Please see "Initial Work..." file that does not have messed up code of the left hand side for commenting.

2024-09-28 16:33 UTC, RobertElliottKrieter commented
https://github.com/elenamiliv/Logic-for-Ontologists-Fall-2024/pull/3

2024-10-15 16:38 UTC, johnbeve requested changes
You only did what I consider to be the easy part of the project, and you didn't complete it. 
If you would like credit for this project, you will need to complete all of the work, have it reviewed by your peers, then submit again.

2024-10-15 16:38 UTC, johnbeve commented on Assignment Part One: Object-Property Pai.html — Logic-for-Ontologists-Fall-2024 [Codespaces: supreme.html
> +When running a reasoner the combination of these becomes undecideable because a functional property must only be only be obtained between one individual and another,
I need more precision in your explanation. I encourage you use variables x, y etc to make clear targets of object properties, among other things.

2024-10-15 16:38 UTC, johnbeve commented on Assignment Part One: Object-Property Pai.html — Logic-for-Ontologists-Fall-2024 [Codespaces: supreme.html
> +    Father_of (Joey, Richard)      = "Joey is father_of Richard"
Why not use variables here too for clarity?

2024-10-15 16:38 UTC, johnbeve commented on Assignment Part One: Object-Property Pai.html — Logic-for-Ontologists-Fall-2024 [Codespaces: supreme.html
> +however, if it is applied transitively it whill carry over to subsequent pairs who are also connected by this same object property.
I do not understand what you are saying here

2024-12-19 01:56 UTC, closed without merging